//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitirixAutomationUsingWebTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://ura.it-solutions.atos.net/");
            request1.ThinkTime = 7;
            request1.ExpectedResponseUrl = "https://ura.it-solutions.atos.net/";
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("https://ura-aa.it-solutions.atos.net/dana-na/auth/url_9/welcome.cgi");
            request2.ThinkTime = 4;
            request2.ExpectedResponseUrl = @"https://wac.das.myatos.net/portal/pki.jsp?DXATargetMethod=GET&DXA-authn-method=Login+Selector&DXATargetUrl=http%3A%2F%2Fwac.das.myatos.net%2Fsso_ura%2FSingleSignOnService%3FSAMLRequest%3DrZJNT8JAEIb%252FSrP3fmFbYEMxKDGSqDSWePBCxnaATcps3dmC%252FHvbYhQvnjzv%250AOzvP8%252B5OGPZVLWeN3dEzvjfI1vnYV8SyP0hFY0hqYMWSYI8sbSHz2eODHHiB%250ArI22utCVcObtnCKwSlMqdtbWLH3%252FCIVXAnv7E1jNHqH1mfW6MeDnirYV5mpL%250AS8rRHFSBwrnTpsCeJBWBcBbzVKzDMk5wk2ziCMZBEiHESRxGYwzxKgniKGpj%250AzA0uiC2QTcUgCEduMHIHw1UwlPFAhuGrcLIv0BtFZbv5b6u3c4jl%252FWqVudky%250AX%252FUXHFSJ5qlN%252Fwi2Ji6Ap6zLumo6efa%252BVUsgcAl8aIX8rkwXqay1IusVW3Vd%250Ap1yHwnlBw31p7WYxnXQ52RuZi2f4mxeY0XTLxfTfwCb%252BBckZq5ad%252FGKe6UoV%250AJ2dWVfp4axBsW0go%252FOl55PdXmn4C%250A%26RelayState%3Dhttps%253A%252F%252Fura-aa.it-solutions.atos.net%252Fura-sso";
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("https://wac.das.myatos.net/sso_pki/authenticate.jsp");
            request3.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request3.ExpectedResponseUrl = "https://wac.das.myatos.net/my.policy_nonce?nonce=U5gzHpAJEEKqMhVC";
            FormPostHttpBody request3Body = new FormPostHttpBody();
            request3Body.FormPostParameters.Add("DXATargetUrl", @"https://wac.das.myatos.net/sso_ura/SingleSignOnService?SAMLRequest=rZJNT8JAEIb%2FSrP3fmFbYEMxKDGSqDSWePBCxnaATcps3dmC%2FHvbYhQvnjzv%0AOzvP8%2B5OGPZVLWeN3dEzvjfI1vnYV8SyP0hFY0hqYMWSYI8sbSHz2eODHHiB%0ArI22utCVcObtnCKwSlMqdtbWLH3%2FCIVXAnv7E1jNHqH1mfW6MeDnirYV5mpL%0AS8rRHFSBwrnTpsCeJBWBcBbzVKzDMk5wk2ziCMZBEiHESRxGYwzxKgniKGpj%0AzA0uiC2QTcUgCEduMHIHw1UwlPFAhuGrcLIv0BtFZbv5b6u3c4jl%2FWqVudky%0AX%2FUXHFSJ5qlN%2Fwi2Ji6Ap6zLumo6efa%2BVUsgcAl8aIX8rkwXqay1IusVW3Vd%0Ap1yHwnlBw31p7WYxnXQ52RuZi2f4mxeY0XTLxfTfwCb%2BBckZq5ad%2FGKe6UoV%0AJ2dWVfp4axBsW0go%2FOl55PdXmn4C%0A&RelayState=https%3A%2F%2Fura-aa.it-solutions.atos.net%2Fura-sso");
            request3Body.FormPostParameters.Add("DXA-target-parameters", "");
            request3Body.FormPostParameters.Add("DXATargetMethod", "GET");
            request3.Body = request3Body;
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("https://wac.das.myatos.net/sso_pki/authenticate.jsp");
            request4.Encoding = System.Text.Encoding.GetEncoding("Windows-1252");
            FormPostHttpBody request4Body = new FormPostHttpBody();
            request4Body.FormPostParameters.Add("dummy", "3d75ae483b47449e3e45d00f8137627b");
            request4.Body = request4Body;
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("https://wac.das.myatos.net/sso_ura/SingleSignOnService");
            request5.Encoding = System.Text.Encoding.GetEncoding("iso-8859-1");
            request5.QueryStringParameters.Add("SAMLRequest", @"rZJNT8JAEIb%2FSrP3fmFbYEMxKDGSqDSWePBCxnaATcps3dmC%2FHvbYhQvnjzv%0AOzvP8%2B5OGPZVLWeN3dEzvjfI1vnYV8SyP0hFY0hqYMWSYI8sbSHz2eODHHiB%0ArI22utCVcObtnCKwSlMqdtbWLH3%2FCIVXAnv7E1jNHqH1mfW6MeDnirYV5mpL%0AS8rRHFSBwrnTpsCeJBWBcBbzVKzDMk5wk2ziCMZBEiHESRxGYwzxKgniKGpj%0AzA0uiC2QTcUgCEduMHIHw1UwlPFAhuGrcLIv0BtFZbv5b6u3c4jl%2FWqVudky%0AX%2FUXHFSJ5qlN%2Fwi2Ji6Ap6zLumo6efa%2BVUsgcAl8aIX8rkwXqay1IusVW3Vd%0Ap1yHwnlBw31p7WYxnXQ52RuZi2f4mxeY0XTLxfTfwCb%2BBckZq5ad%2FGKe6UoV%0AJ2dWVfp4axBsW0go%2FOl55PdXmn4C%0A", false, false);
            request5.QueryStringParameters.Add("RelayState", "https%3A%2F%2Fura-aa.it-solutions.atos.net%2Fura-sso", false, false);
            FormPostHttpBody request5Body = new FormPostHttpBody();
            request5.Body = request5Body;
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("https://ura-aa.it-solutions.atos.net/dana-na/auth/saml-consumer.cgi");
            request6.ThinkTime = 1;
            request6.ExpectedResponseUrl = "https://ura-aa.it-solutions.atos.net/dana-na/auth/url_14/welcome.cgi?p=preauth&id" +
                "=state_2e628e7abeaa2fca1a9908338dfcb00f&signinRealmId=18";
            FormPostHttpBody request6Body = new FormPostHttpBody();
            request6Body.FormPostParameters.Add("SAMLResponse", "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c2FtbDJwOlJlc3BvbnNlIHhtbG5zO" +
                    "nNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiBEZXN0aW5hdGlvbj0ia" +
                    "HR0cHM6Ly91cmEtYWEuaXQtc29sdXRpb25zLmF0b3MubmV0L2RhbmEtbmEvYXV0aC9zYW1sLWNvbnN1b" +
                    "WVyLmNnaSIgSUQ9InV1aWQtMDdmZmY0Y2YtNmQ1Zi00YmJmLThjOTAtYWE5MGM4M2VlYTMxIiBJblJlc" +
                    "3BvbnNlVG89Il8xZDU2ZWY2ZjU0YTkwNjRlYTU2NTE0OWUxZTM2MDU0NCIgSXNzdWVJbnN0YW50PSIyM" +
                    "DE4LTA4LTI3VDA3OjUyOjM2LjU0NloiIFZlcnNpb249IjIuMCI+PHNhbWwyOklzc3VlciB4bWxuczpzY" +
                    "W1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+d2FjLmRhcy5teWF0b3Mub" +
                    "mV0PC9zYW1sMjpJc3N1ZXI+PGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvM" +
                    "jAwMC8wOS94bWxkc2lnIyI+PGRzOlNpZ25lZEluZm8+PGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQ" +
                    "Wxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48ZHM6U2lnb" +
                    "mF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3JzY" +
                    "S1zaGExIi8+PGRzOlJlZmVyZW5jZSBVUkk9IiN1dWlkLTA3ZmZmNGNmLTZkNWYtNGJiZi04YzkwLWFhO" +
                    "TBjODNlZWEzMSI+PGRzOlRyYW5zZm9ybXM+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d" +
                    "3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIi8+PGRzOlRyYW5zZm9yb" +
                    "SBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvZHM6V" +
                    "HJhbnNmb3Jtcz48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwM" +
                    "C8wOS94bWxkc2lnI3NoYTEiLz48ZHM6RGlnZXN0VmFsdWU+SzRoeEt5YzFZTkhLL2Y4ekcyOHpjTG82Y" +
                    "W40PTwvZHM6RGlnZXN0VmFsdWU+PC9kczpSZWZlcmVuY2U+PC9kczpTaWduZWRJbmZvPjxkczpTaWduY" +
                    "XR1cmVWYWx1ZT4NClFnRjJ3M1MyMUN1WFRyb3VyYlpZdENOU2xlNjlzSm41cm0wL295UTlYa2hKUENlZ" +
                    "EQvWTdPUTBYVEVWM09nbXpQaE1LbEtGYXFyL3ANClBvRmVNWHZEVEZxVkpjSllGQUpsTXFSd2RqNnFVM" +
                    "FBpMUJGQlYzZmh4UXZrUkR1a242d1lrWUVIS3BtU3N0M0JqSThPUkxBeVJ2TEMNCkp5NUpBVWJMZFhQZ" +
                    "lNVdktzcTdDK1VHbllGYzBnUENCWmtUWkg5dU5pR0ltbW5lRlpyUWZQQUFYU254QmxjNzJMYzdJcjZpS" +
                    "UxYd1kNCmMvUVQrM29nNXV4S2ZTNlpnV2ZRdWxUY0k2VlYrNWNKYk4vZ3UvUlQ3TzBQcGUwVmU1d1pkd" +
                    "EJTajYvZlBFVlpBdDhPNWJ0OFNHbDUNCjdVbjFsbzQwLzFPZ3ZiY3ppcTdzL0dmWWc0NWxPd1F5U2NKU" +
                    "EF3PT0NCjwvZHM6U2lnbmF0dXJlVmFsdWU+PGRzOktleUluZm8+PGRzOlg1MDlEYXRhPjxkczpYNTA5Q" +
                    "2VydGlmaWNhdGU+TUlJRkl6Q0NCQXVnQXdJQkFnSU5BT2VIVzBRQUFBQUFVTmE1cERBTkJna3Foa2lHO" +
                    "XcwQkFRc0ZBRENCdWpFTE1Ba0dBMVVFQmhNQ1ZWTXhGakFVQmdOVkJBb1REVVZ1ZEhKMWMzUXNJRWx1W" +
                    "Xk0eEtEQW1CZ05WQkFzVEgxTmxaU0IzZDNjdVpXNTBjblZ6ZEM1dVpYUXZiR1ZuWVd3dGRHVnliWE14T" +
                    "1RBM0JnTlZCQXNUTUNoaktTQXlNREV5SUVWdWRISjFjM1FzSUVsdVl5NGdMU0JtYjNJZ1lYVjBhRzl5Y" +
                    "VhwbFpDQjFjMlVnYjI1c2VURXVNQ3dHQTFVRUF4TWxSVzUwY25WemRDQkRaWEowYVdacFkyRjBhVzl1S" +
                    "UVGMWRHaHZjbWwwZVNBdElFd3hTekFlRncweE5qQXhNVGt4TkRFMU16aGFGdzB4T1RBeE1Ua3hORFExT" +
                    "XpkYU1GNHhDekFKQmdOVkJBWVRBa1pTTVE4d0RRWURWUVFIRXdaQ1pYcHZibk14RFRBTEJnTlZCQW9UQ" +
                    "kVGMGIzTXhEVEFMQmdOVkJBc1RCRUYwYjNNeElEQWVCZ05WQkFNVEYzTmhiV3d5TURFMkxYQnlaQzV0Z" +
                    "VdGMGIzTXVibVYwTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFsM0RmW" +
                    "VFSS2lQdlpYS3ZZa0ZUVThDNC9uTWNhS0FtOE9lL1lhU1VxZzF0Zk1jQThoR203czlXQTZFblNrWkYzO" +
                    "GtFRkpFV2V2UFh3S3pkTEcxak5Nbk1TWEc1TkZ0cXJwU1czTko3QzBQTEFTNFFRQXlsZlBZdnBJSFU0d" +
                    "y9FZVdXOG1TZ0F0NU82eFVReEhjYnJQUmNJWFM4WThoaFFxVUY2MWNvTHQxSkJlc3ZDSzJUTVZUSHhYL" +
                    "1RjTVE3VkxhWFNqd2hWZDBmNzh3U0ptVjJWeGF5UEFlRVVXZXl6Y2FjTnQzZTBxQmpxd1JlVXBJSDl6W" +
                    "klvWEdEMHNHc1dMd3c2NXJXVUxKajFXazEyY3JVOXBhd3plQjJHYy9CQm1ZQlZzb3JnazluRVBkZlcwS" +
                    "mErUlR5cDFTbXRuY2NWY2lIODZsL0ZpZU9CN1hiRFdyQiticlFJREFRQUJvNElCZ1RDQ0FYMHdDd1lEV" +
                    "lIwUEJBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1ETUdBMVVkSHdRc01Db3dLS0Ftb" +
                    "0NTR0ltaDBkSEE2THk5amNtd3VaVzUwY25WemRDNXVaWFF2YkdWMlpXd3hheTVqY213d1N3WURWUjBnQ" +
                    "kVRd1FqQTJCZ3BnaGtnQmh2cHNDZ0VGTUNnd0pnWUlLd1lCQlFVSEFnRVdHbWgwZEhBNkx5OTNkM2N1W" +
                    "lc1MGNuVnpkQzV1WlhRdmNuQmhNQWdHQm1lQkRBRUNBakJvQmdnckJnRUZCUWNCQVFSY01Gb3dJd1lJS" +
                    "3dZQkJRVUhNQUdHRjJoMGRIQTZMeTl2WTNOd0xtVnVkSEoxYzNRdWJtVjBNRE1HQ0NzR0FRVUZCekFDa" +
                    "Glkb2RIUndPaTh2WVdsaExtVnVkSEoxYzNRdWJtVjBMMnd4YXkxamFHRnBiakkxTmk1alpYSXdJZ1lEV" +
                    "lIwUkJCc3dHWUlYYzJGdGJESXdNVFl0Y0hKa0xtMTVZWFJ2Y3k1dVpYUXdId1lEVlIwakJCZ3dGb0FVZ" +
                    "3FKd2ROMjhVei9QZTlUM3pYK25ZTVlLVEw4d0hRWURWUjBPQkJZRUZHUDZwaUErMGZtWlVtY25oNkZvM" +
                    "1dLZTRkRGdNQWtHQTFVZEV3UUNNQUF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUROL3ZHQ0J4eHVXe" +
                    "U52ejRtT3l1UERZWG9mcXhRVnRPZCtLZkhaTmpUbGtjN3Z6eHhYM2VUdFdEYW1Ma2QrNWJWT1lBZ2dZV" +
                    "jgranYzVHg5RXU2VkkydCsvdzJDWXNJV1p6bFZYNmxwZWJLQnZFcG5MOWI0TEVOVEJOSnpsQlB1SFozW" +
                    "ThIa084RjFiNGc5U1krR25STGxDbjV3ejI0OWpuMExpdk5Rek9mMVdFVTNBMmlNaFZhbUFBREdnYys4U" +
                    "3liYVNsM25KWWM1Yjc0OWdkeXdCQjFiblEvNVF4K2o2a1NJeFJ4WGtXUFRoWVZmcllVUnlnMDBhYmt0U" +
                    "y9MTDR5VmVwdnhJejRsVGlGUktwK0VCa1ZSUXlwOXhnY1AxR0Q5TFc2YkltelVIMU81WmFGUjRwdC8xd" +
                    "VpGaldCaXc1SWpUd2VubDNJT1BCNWFSWFRWSzRGdz08L2RzOlg1MDlDZXJ0aWZpY2F0ZT48L2RzOlg1M" +
                    "DlEYXRhPjxkczpYNTA5RGF0YT48ZHM6WDUwOUNlcnRpZmljYXRlPk1JSUZEakNDQS9hZ0F3SUJBZ0lNR" +
                    "HVsTXd3QUFBQUJSMDNlRk1BMEdDU3FHU0liM0RRRUJDd1VBTUlHK01Rc3dDUVlEVlFRR0V3SlZVekVXT" +
                    "UJRR0ExVUVDaE1OUlc1MGNuVnpkQ3dnU1c1akxqRW9NQ1lHQTFVRUN4TWZVMlZsSUhkM2R5NWxiblJ5Z" +
                    "FhOMExtNWxkQzlzWldkaGJDMTBaWEp0Y3pFNU1EY0dBMVVFQ3hNd0tHTXBJREl3TURrZ1JXNTBjblZ6Z" +
                    "EN3Z1NXNWpMaUF0SUdadmNpQmhkWFJvYjNKcGVtVmtJSFZ6WlNCdmJteDVNVEl3TUFZRFZRUURFeWxGY" +
                    "m5SeWRYTjBJRkp2YjNRZ1EyVnlkR2xtYVdOaGRHbHZiaUJCZFhSb2IzSnBkSGtnTFNCSE1qQWVGdzB4T" +
                    "lRFd01EVXhPVEV6TlRaYUZ3MHpNREV5TURVeE9UUXpOVFphTUlHNk1Rc3dDUVlEVlFRR0V3SlZVekVXT" +
                    "UJRR0ExVUVDaE1OUlc1MGNuVnpkQ3dnU1c1akxqRW9NQ1lHQTFVRUN4TWZVMlZsSUhkM2R5NWxiblJ5Z" +
                    "FhOMExtNWxkQzlzWldkaGJDMTBaWEp0Y3pFNU1EY0dBMVVFQ3hNd0tHTXBJREl3TVRJZ1JXNTBjblZ6Z" +
                    "EN3Z1NXNWpMaUF0SUdadmNpQmhkWFJvYjNKcGVtVmtJSFZ6WlNCdmJteDVNUzR3TEFZRFZRUURFeVZGY" +
                    "m5SeWRYTjBJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNUlDMGdUREZMTUlJQklqQU5CZ2txa" +
                    "GtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyaitXMEUyNUwwVG4yemxlbTFEdVhLVmgya0ZuV" +
                    "XdtcUFKcU9WMzhwYTl2SDRTRWtxanJRalVjajB1MXlGdkNSSWRKZHQ3aExxSU9QdDVFeWFNL09KWk1zc" +
                    "24yWHlQN0J0QmU2Q1o0RGtKTjdmRW1ESW1pS205NUh3ekdZZWk1OVFBdlM3ejdUc295cWowaXAvd0RvS" +
                    "1ZnRzk3YVRXcFJ6SmlhdFdBN2xRcmpWNm5ONVpHaFRKYmlFejVSNnJnWkZES05yVGRER3Z1b1lwRGJ3a" +
                    "3JLNkhJaVBPbEovOTE1dGd4eWQ4Qi9sdzliZHBYaVNQYkJ0TE9ySno1UkJHWEZFYUxwSFBBVHBYYm8rO" +
                    "ERYM0ZiYWU4aTRWSGo5SHlNZzRwM05GWFUyd083R09GeWszNnQwRkFTSzdsRFlxalZzMS9sTVpMd2hHd" +
                    "1NxekdtSWRUaXZaR3dJREFRQUJvNElCRERDQ0FRZ3dEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkR" +
                    "XdFQi93UUlNQVlCQWY4Q0FRQXdNd1lJS3dZQkJRVUhBUUVFSnpBbE1DTUdDQ3NHQVFVRkJ6QUJoaGRvZ" +
                    "EhSd09pOHZiMk56Y0M1bGJuUnlkWE4wTG01bGREQXdCZ05WSFI4RUtUQW5NQ1dnSTZBaGhoOW9kSFJ3T" +
                    "2k4dlkzSnNMbVZ1ZEhKMWMzUXVibVYwTDJjeVkyRXVZM0pzTURzR0ExVWRJQVEwTURJd01BWUVWUjBnQ" +
                    "URBb01DWUdDQ3NHQVFVRkJ3SUJGaHBvZEhSd09pOHZkM2QzTG1WdWRISjFjM1F1Ym1WMEwzSndZVEFkQ" +
                    "mdOVkhRNEVGZ1FVZ3FKd2ROMjhVei9QZTlUM3pYK25ZTVlLVEw4d0h3WURWUjBqQkJnd0ZvQVVhbkltZ" +
                    "XRBZTczM25PMmxSMUd5Tm41QVNacXN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQURuVmpwaURZY2dzW" +
                    "TlOd0hSa3d5L1lKck14cDFjbmNOMEh5TWcvdmRNTlk5bmduQ1RRSWxaSXYxOSs0by8wT2dlbWtuTk0vV" +
                    "FdnckZURUtGY3hTQkpQb2sxREQyYkhpNFdpM09nbDA4VFJZQ2o5M21FQzQ1bWovWGVUSVJzWHNnZGZKZ" +
                    "2hoY2c4NXgyTHkvckprQ2s5dVVtSVRTbkthMS9seTc4RXF2SWF6Q1Awa2taOVl1anMrc3pHUVZHSExsY" +
                    "khmVFVxaTUzWTJzQUVvMUdkUnZjNk4xNzJ0a3crQ05neEtoaXVjT2hrM1l0Q0Fidm1xbGpFdG9adU1ye" +
                    "DFnTCsxWVExSkg3SGRNeFdCQ01ST04xZXhDZHRUaXg5cXJLZ1dSczZQTGlnVldYVVgvaHdpZFFvc2s4V" +
                    "3dCRDlsdTUxYVg4L3dkUVFHY0hzRlh3dDM1dUxjdz08L2RzOlg1MDlDZXJ0aWZpY2F0ZT48L2RzOlg1M" +
                    "DlEYXRhPjxkczpYNTA5RGF0YT48ZHM6WDUwOUNlcnRpZmljYXRlPk1JSUUvekNDQStlZ0F3SUJBZ0lFV" +
                    "WROQVJEQU5CZ2txaGtpRzl3MEJBUXNGQURDQnNERUxNQWtHQTFVRUJoTUNWVk14RmpBVUJnTlZCQW9UR" +
                    "FVWdWRISjFjM1FzSUVsdVl5NHhPVEEzQmdOVkJBc1RNSGQzZHk1bGJuUnlkWE4wTG01bGRDOURVRk1nY" +
                    "VhNZ2FXNWpiM0p3YjNKaGRHVmtJR0o1SUhKbFptVnlaVzVqWlRFZk1CMEdBMVVFQ3hNV0tHTXBJREl3T" +
                    "URZZ1JXNTBjblZ6ZEN3Z1NXNWpMakV0TUNzR0ExVUVBeE1rUlc1MGNuVnpkQ0JTYjI5MElFTmxjblJwW" +
                    "m1sallYUnBiMjRnUVhWMGFHOXlhWFI1TUI0WERURTBNRGt5TWpFM01UUTFOMW9YRFRJME1Ea3lNekF4T" +
                    "XpFMU0xb3dnYjR4Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MUZiblJ5ZFhOMExDQkpibU11T" +
                    "VNnd0pnWURWUVFMRXg5VFpXVWdkM2QzTG1WdWRISjFjM1F1Ym1WMEwyeGxaMkZzTFhSbGNtMXpNVGt3T" +
                    "ndZRFZRUUxFekFvWXlrZ01qQXdPU0JGYm5SeWRYTjBMQ0JKYm1NdUlDMGdabTl5SUdGMWRHaHZjbWw2W" +
                    "ldRZ2RYTmxJRzl1YkhreE1qQXdCZ05WQkFNVEtVVnVkSEoxYzNRZ1VtOXZkQ0JEWlhKMGFXWnBZMkYwY" +
                    "Vc5dUlFRjFkR2h2Y21sMGVTQXRJRWN5TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ" +
                    "2dLQ0FRRUF1b1MyY3R1ZURHdmltZWt3QWFkMjZqSzRsVUVheWRwaFRsaHl6LzcyZ25tL2MyRUdDcVVuM" +
                    "kxOZjAwVk9ISExXVGpMeWNvb1A5NE1aMEdxQWdBQkZIckRINTVxL0VsY25IS05vTHdxSHZXcHJEbDVsO" +
                    "Hh4MzFkU0ZqWEFodExNeTU0dWkxWVk1QXJHNDBrZk81TWxKeER1bjN2dFVmVmUrOE9odXdubXlPZ3RWN" +
                    "GxDWUZqSVRYQzk0VnNIQ2xMUHlXdVFubXA4azE4YnMwSnNsZ3VQTXdzUkZ4WXlYZWdacktoR2ZxUXB1U" +
                    "0R0djI5UVJHVUwzandlLzlWTmZuRDcwRnl6bWFheE9Na3hpZCtxMzZPVzdOTHdaaTY2Y1VlZTNmclZUc" +
                    "1RNaTVXM1BjRHdhK3VLYlo3YUQ5STJscjJKTVRlQllyR1EwRWdQNHRvMlVZeVNrY1FJREFRQUJvNElCR" +
                    "HpDQ0FRc3dEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRRXdNd1lJS" +
                    "3dZQkJRVUhBUUVFSnpBbE1DTUdDQ3NHQVFVRkJ6QUJoaGRvZEhSd09pOHZiMk56Y0M1bGJuUnlkWE4wT" +
                    "G01bGREQXpCZ05WSFI4RUxEQXFNQ2lnSnFBa2hpSm9kSFJ3T2k4dlkzSnNMbVZ1ZEhKMWMzUXVibVYwT" +
                    "DNKdmIzUmpZVEV1WTNKc01Ec0dBMVVkSUFRME1ESXdNQVlFVlIwZ0FEQW9NQ1lHQ0NzR0FRVUZCd0lCR" +
                    "mhwb2RIUndPaTh2ZDNkM0xtVnVkSEoxYzNRdWJtVjBMME5RVXpBZEJnTlZIUTRFRmdRVWFuSW1ldEFlN" +
                    "zMzbk8ybFIxR3lObjVBU1pxc3dId1lEVlIwakJCZ3dGb0FVYUpEa1o2U21VNERIaG1hazhmZExRL3VFd" +
                    "lcwd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHa3pnL3dvZW05OTc1MVY2OFUrZXAxMXM4ekRPRGJaT" +
                    "ktJb2FCanFIbW5UdmVmUWQ5cTRBSU5PU3M5djBmSEJJajkwNVBlWVNaNmJ0cDdoMjVoM0xWWTBzYWc4M" +
                    "mYzQXpjZS9CUVBVQXNYeDVjYmFDS1VUeDJJakVkRmhNQjFnaEVYdmVhakdKcE9rdDgwMHVHbkZFL2FSc" +
                    "zhsRmMzYTJrdloyQ2x2aEEwZTM2U2xNa1RJak4wcWNOZGg0L1IwZjVJT0pKSUN0dC9uUDVGMmwxSEhFa" +
                    "FZ0d0g5cy9IQUhyR2tVbU1SVE1aYjluM3NyTU0yWGxRWkhYTjc1QkdwYWQ1b3FYbmFmT3JFNmFQYjBCb" +
                    "0dyWlR5SUFpMFRWYVdKN0x1dk11dWVTZldsblBmeTRmTjVCaDlCcDZyb0tHSG9hbFVPemVYRW9kbTJoK" +
                    "zFkSzdFM0lEaEE9PC9kczpYNTA5Q2VydGlmaWNhdGU+PC9kczpYNTA5RGF0YT48ZHM6WDUwOURhdGE+P" +
                    "GRzOlg1MDlDZXJ0aWZpY2F0ZT5NSUlFa1RDQ0EzbWdBd0lCQWdJRVJXdFFWREFOQmdrcWhraUc5dzBCQ" +
                    "VFVRkFEQ0JzREVMTUFrR0ExVUVCaE1DVlZNeEZqQVVCZ05WQkFvVERVVnVkSEoxYzNRc0lFbHVZeTR4T" +
                    "1RBM0JnTlZCQXNUTUhkM2R5NWxiblJ5ZFhOMExtNWxkQzlEVUZNZ2FYTWdhVzVqYjNKd2IzSmhkR1ZrS" +
                    "UdKNUlISmxabVZ5Wlc1alpURWZNQjBHQTFVRUN4TVdLR01wSURJd01EWWdSVzUwY25WemRDd2dTVzVqT" +
                    "GpFdE1Dc0dBMVVFQXhNa1JXNTBjblZ6ZENCU2IyOTBJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5Y" +
                    "VhSNU1CNFhEVEEyTVRFeU56SXdNak0wTWxvWERUSTJNVEV5TnpJd05UTTBNbG93Z2JBeEN6QUpCZ05WQ" +
                    "kFZVEFsVlRNUll3RkFZRFZRUUtFdzFGYm5SeWRYTjBMQ0JKYm1NdU1Ua3dOd1lEVlFRTEV6QjNkM2N1W" +
                    "lc1MGNuVnpkQzV1WlhRdlExQlRJR2x6SUdsdVkyOXljRzl5WVhSbFpDQmllU0J5WldabGNtVnVZMlV4S" +
                    "HpBZEJnTlZCQXNURmloaktTQXlNREEySUVWdWRISjFjM1FzSUVsdVl5NHhMVEFyQmdOVkJBTVRKRVZ1Z" +
                    "EhKMWMzUWdVbTl2ZENCRFpYSjBhV1pwWTJGMGFXOXVJRUYxZEdodmNtbDBlVENDQVNJd0RRWUpLb1pJa" +
                    "HZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMYVZ0a05DK3NadEttOUkzNVJNT1ZjRjdzTjVFVUZvT" +
                    "nUzcy9wb0JqNkU0S1B6M0VFWm1MazBlR3JFYVRzYlJ3SldJc01uL01Zc3pBOXUzZzNzK0lJUmU3YkpXS" +
                    "0tmNDRMbEFjVGZGeTBjT2x5cG93Q0tWWWhYYlI5bjEwQ3YvZ2t2SnJUN2VUTnVRZ0ZBL0NZcUVBT3d3Q" +
                    "2owWXpmdjlLbG1hSTVVWExFV2VIMjVEZVcwTVhKaitTS2ZGSTBkY1h2MXU1eDYwOW1oRjBZYURXNktLa" +
                    "mJIaktZRCtKWEdJcmI2OGo2eFNsa3VxVVkza0V6RVo2RTVObjl1c3MyclZ2RGxVY2NwNmVuK1EzWDBkZ" +
                    "05tQnUxa213aEgrNXBQaTk0RGtaZnMwTnc0cGdIQk5yemlHTHA1L1Y2K2VGNjdySE1zb0lWKzJITmpub" +
                    "2dRaStkUGEyTXNDQXdFQUFhT0JzRENCclRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQ" +
                    "kFVd0F3RUIvekFyQmdOVkhSQUVKREFpZ0E4eU1EQTJNVEV5TnpJd01qTTBNbHFCRHpJd01qWXhNVEkzT" +
                    "WpBMU16UXlXakFmQmdOVkhTTUVHREFXZ0JSb2tPUm5wS1pUZ01lR1pxVHg5MHREKzRTOWJUQWRCZ05WS" +
                    "FE0RUZnUVVhSkRrWjZTbVU0REhobWFrOGZkTFEvdUV2VzB3SFFZSktvWklodlo5QjBFQUJCQXdEaHNJV" +
                    "mpjdU1UbzBMakFEQWdTUU1BMEdDU3FHU0liM0RRRUJCUVVBQTRJQkFRQ1QxREN3MXdNZ0t0RDVZK2lSR" +
                    "EFVZ3FWOFp5bnR5VHRTeDI5Q1crMVJhR1N3TUNQZXl2SVdvblg5dE8xS3pLdHZuMUlTTVkvWVB5eVlCa" +
                    "1ZCczlGOFU0cE4wd0JPZU1EcFE0N1JneFJ6d0lrU05jVWVzeUJySjZadWFBR0FULzNCK1h4Rk5TUnV6R" +
                    "lZKN3lWVGF2NTJWcjJ1YTJKN3A4ZVJEamVJUlJEcS9yNzJEUW5OU2k2cTdweW5QOVdRY0NrM1J2S3Fzb" +
                    "nlyUS8zOS8ybjNxc2Uwd0pjR0UyalRTVzNpRFZ1eWNOc01tNGhIMlowa2RrcXVNKyt2L2V1NkZTcWRRZ" +
                    "1BDblhFcVVMbDhGbVR4U1FlRE50R1BQQVVPNm5JUGNqMkE3ODFxMHRIdXUyZ3VRT0hYdmdSMW0wdmRYY" +
                    "0RhenYvd29yM0VsaFZzVC9oNS9XclE4PC9kczpYNTA5Q2VydGlmaWNhdGU+PC9kczpYNTA5RGF0YT48L" +
                    "2RzOktleUluZm8+PC9kczpTaWduYXR1cmU+PHNhbWwycDpTdGF0dXM+PHNhbWwycDpTdGF0dXNDb2RlI" +
                    "FZhbHVlPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6c3RhdHVzOlN1Y2Nlc3MiLz48L3NhbWwyc" +
                    "DpTdGF0dXM+PHNhbWwyOkFzc2VydGlvbiB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBT" +
                    "Uw6Mi4wOmFzc2VydGlvbiIgSUQ9InV1aWQtOWQ2MzNiNDktZTE2NC00ZTIyLWJhNGYtOWMzYzFiYjQyN" +
                    "zc2IiBJc3N1ZUluc3RhbnQ9IjIwMTgtMDgtMjdUMDc6NTI6MDYuNjIzWiIgVmVyc2lvbj0iMi4wIj48c" +
                    "2FtbDI6SXNzdWVyPndhYy5kYXMubXlhdG9zLm5ldDwvc2FtbDI6SXNzdWVyPjxkczpTaWduYXR1cmUge" +
                    "G1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPjxkczpTaWduZWRJbmZvP" +
                    "jxkczpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwM" +
                    "S8xMC94bWwtZXhjLWMxNG4jIi8+PGRzOlNpZ25hdHVyZU1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d" +
                    "3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNyc2Etc2hhMSIvPjxkczpSZWZlcmVuY2UgVVJJPSIjdXVpZ" +
                    "C05ZDYzM2I0OS1lMTY0LTRlMjItYmE0Zi05YzNjMWJiNDI3NzYiPjxkczpUcmFuc2Zvcm1zPjxkczpUc" +
                    "mFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvc" +
                    "GVkLXNpZ25hdHVyZSIvPjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yM" +
                    "DAxLzEwL3htbC1leGMtYzE0biMiLz48L2RzOlRyYW5zZm9ybXM+PGRzOkRpZ2VzdE1ldGhvZCBBbGdvc" +
                    "ml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNzaGExIi8+PGRzOkRpZ2VzdFZhb" +
                    "HVlPkxWSDI4TU0yYUNabGU3dnJuS3Fwblg2YW94UT08L2RzOkRpZ2VzdFZhbHVlPjwvZHM6UmVmZXJlb" +
                    "mNlPjwvZHM6U2lnbmVkSW5mbz48ZHM6U2lnbmF0dXJlVmFsdWU+DQpRenJhTXV4UldhMTMzbEF4M2hPQ" +
                    "mxBOVpJUHI2b1BhQjA4REYvMGRPVHFuTDJMR0xodHMxa3pLVzlLNWh2RnVvR2lXN1JIaHZZdm1yDQpyW" +
                    "Ul0RlJvS3IwY1BmVEJVd0VVMFh3RS9jaGlGME02RjdZTzc2S3ZrbFRHeXYvQjRhZG5GbXYvZG5FUytjO" +
                    "TVrTzNNckh4OXlpZU4vDQprOTUyK0FzdGZxMVY3dFB4Tk1MZllSOXFtYzFBZW5VcmdrellrWXRCcm5HN" +
                    "TIrZGM5NjRvK1ZGQzkrNEo0bm55aGRDU1lxYlFBYVVzDQpMdXluR1RpQk44N0xyek82b0NGOFVLQnp6c" +
                    "ThYOGN2YXBwbThGb21LNksveGNlVVI5NlVWWUdMdklhSmllcXR0dkgvTllFcHdSRGdrDQpRKzY2RS9HQ" +
                    "nJwaXIvallXb3pBb2srK0dmYklXRGh0amREc0wvQT09DQo8L2RzOlNpZ25hdHVyZVZhbHVlPjxkczpLZ" +
                    "XlJbmZvPjxkczpYNTA5RGF0YT48ZHM6WDUwOUNlcnRpZmljYXRlPk1JSUZJekNDQkF1Z0F3SUJBZ0lOQ" +
                    "U9lSFcwUUFBQUFBVU5hNXBEQU5CZ2txaGtpRzl3MEJBUXNGQURDQnVqRUxNQWtHQTFVRUJoTUNWVk14R" +
                    "mpBVUJnTlZCQW9URFVWdWRISjFjM1FzSUVsdVl5NHhLREFtQmdOVkJBc1RIMU5sWlNCM2QzY3VaVzUwY" +
                    "25WemRDNXVaWFF2YkdWbllXd3RkR1Z5YlhNeE9UQTNCZ05WQkFzVE1DaGpLU0F5TURFeUlFVnVkSEoxY" +
                    "zNRc0lFbHVZeTRnTFNCbWIzSWdZWFYwYUc5eWFYcGxaQ0IxYzJVZ2IyNXNlVEV1TUN3R0ExVUVBeE1sU" +
                    "lc1MGNuVnpkQ0JEWlhKMGFXWnBZMkYwYVc5dUlFRjFkR2h2Y21sMGVTQXRJRXd4U3pBZUZ3MHhOakF4T" +
                    "VRreE5ERTFNemhhRncweE9UQXhNVGt4TkRRMU16ZGFNRjR4Q3pBSkJnTlZCQVlUQWtaU01ROHdEUVlEV" +
                    "lFRSEV3WkNaWHB2Ym5NeERUQUxCZ05WQkFvVEJFRjBiM014RFRBTEJnTlZCQXNUQkVGMGIzTXhJREFlQ" +
                    "mdOVkJBTVRGM05oYld3eU1ERTJMWEJ5WkM1dGVXRjBiM011Ym1WME1JSUJJakFOQmdrcWhraUc5dzBCQ" +
                    "VFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbDNEZllRUktpUHZaWEt2WWtGVFU4QzQvbk1jYUtBbThPZS9ZY" +
                    "VNVcWcxdGZNY0E4aEdtN3M5V0E2RW5Ta1pGMzhrRUZKRVdldlBYd0t6ZExHMWpOTW5NU1hHNU5GdHFyc" +
                    "FNXM05KN0MwUExBUzRRUUF5bGZQWXZwSUhVNHcvRWVXVzhtU2dBdDVPNnhVUXhIY2JyUFJjSVhTOFk4a" +
                    "GhRcVVGNjFjb0x0MUpCZXN2Q0syVE1WVEh4WC9UY01RN1ZMYVhTandoVmQwZjc4d1NKbVYyVnhheVBBZ" +
                    "UVVV2V5emNhY050M2UwcUJqcXdSZVVwSUg5elpJb1hHRDBzR3NXTHd3NjVyV1VMSmoxV2sxMmNyVTlwY" +
                    "Xd6ZUIyR2MvQkJtWUJWc29yZ2s5bkVQZGZXMEphK1JUeXAxU210bmNjVmNpSDg2bC9GaWVPQjdYYkRXc" +
                    "kIrYnJRSURBUUFCbzRJQmdUQ0NBWDB3Q3dZRFZSMFBCQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQ" +
                    "VFVRkJ3TUJNRE1HQTFVZEh3UXNNQ293S0tBbW9DU0dJbWgwZEhBNkx5OWpjbXd1Wlc1MGNuVnpkQzV1W" +
                    "lhRdmJHVjJaV3d4YXk1amNtd3dTd1lEVlIwZ0JFUXdRakEyQmdwZ2hrZ0JodnBzQ2dFRk1DZ3dKZ1lJS" +
                    "3dZQkJRVUhBZ0VXR21oMGRIQTZMeTkzZDNjdVpXNTBjblZ6ZEM1dVpYUXZjbkJoTUFnR0JtZUJEQUVDQ" +
                    "WpCb0JnZ3JCZ0VGQlFjQkFRUmNNRm93SXdZSUt3WUJCUVVITUFHR0YyaDBkSEE2THk5dlkzTndMbVZ1Z" +
                    "EhKMWMzUXVibVYwTURNR0NDc0dBUVVGQnpBQ2hpZG9kSFJ3T2k4dllXbGhMbVZ1ZEhKMWMzUXVibVYwT" +
                    "DJ3eGF5MWphR0ZwYmpJMU5pNWpaWEl3SWdZRFZSMFJCQnN3R1lJWGMyRnRiREl3TVRZdGNISmtMbTE1W" +
                    "VhSdmN5NXVaWFF3SHdZRFZSMGpCQmd3Rm9BVWdxSndkTjI4VXovUGU5VDN6WCtuWU1ZS1RMOHdIUVlEV" +
                    "lIwT0JCWUVGR1A2cGlBKzBmbVpVbWNuaDZGbzNXS2U0ZERnTUFrR0ExVWRFd1FDTUFBd0RRWUpLb1pJa" +
                    "HZjTkFRRUxCUUFEZ2dFQkFETi92R0NCeHh1V3lOdno0bU95dVBEWVhvZnF4UVZ0T2QrS2ZIWk5qVGxrY" +
                    "zd2enh4WDNlVHRXRGFtTGtkKzViVk9ZQWdnWVY4K2p2M1R4OUV1NlZJMnQrL3cyQ1lzSVdaemxWWDZsc" +
                    "GViS0J2RXBuTDliNExFTlRCTkp6bEJQdUhaM1k4SGtPOEYxYjRnOVNZK0duUkxsQ241d3oyNDlqbjBMa" +
                    "XZOUXpPZjFXRVUzQTJpTWhWYW1BQURHZ2MrOFN5YmFTbDNuSlljNWI3NDlnZHl3QkIxYm5RLzVReCtqN" +
                    "mtTSXhSeFhrV1BUaFlWZnJZVVJ5ZzAwYWJrdFMvTEw0eVZlcHZ4SXo0bFRpRlJLcCtFQmtWUlF5cDl4Z" +
                    "2NQMUdEOUxXNmJJbXpVSDFPNVphRlI0cHQvMXVaRmpXQml3NUlqVHdlbmwzSU9QQjVhUlhUVks0Rnc9P" +
                    "C9kczpYNTA5Q2VydGlmaWNhdGU+PC9kczpYNTA5RGF0YT48ZHM6WDUwOURhdGE+PGRzOlg1MDlDZXJ0a" +
                    "WZpY2F0ZT5NSUlGRGpDQ0EvYWdBd0lCQWdJTUR1bE13d0FBQUFCUjAzZUZNQTBHQ1NxR1NJYjNEUUVCQ" +
                    "3dVQU1JRytNUXN3Q1FZRFZRUUdFd0pWVXpFV01CUUdBMVVFQ2hNTlJXNTBjblZ6ZEN3Z1NXNWpMakVvT" +
                    "UNZR0ExVUVDeE1mVTJWbElIZDNkeTVsYm5SeWRYTjBMbTVsZEM5c1pXZGhiQzEwWlhKdGN6RTVNRGNHQ" +
                    "TFVRUN4TXdLR01wSURJd01Ea2dSVzUwY25WemRDd2dTVzVqTGlBdElHWnZjaUJoZFhSb2IzSnBlbVZrS" +
                    "UhWelpTQnZibXg1TVRJd01BWURWUVFERXlsRmJuUnlkWE4wSUZKdmIzUWdRMlZ5ZEdsbWFXTmhkR2x2Y" +
                    "mlCQmRYUm9iM0pwZEhrZ0xTQkhNakFlRncweE5URXdNRFV4T1RFek5UWmFGdzB6TURFeU1EVXhPVFF6T" +
                    "lRaYU1JRzZNUXN3Q1FZRFZRUUdFd0pWVXpFV01CUUdBMVVFQ2hNTlJXNTBjblZ6ZEN3Z1NXNWpMakVvT" +
                    "UNZR0ExVUVDeE1mVTJWbElIZDNkeTVsYm5SeWRYTjBMbTVsZEM5c1pXZGhiQzEwWlhKdGN6RTVNRGNHQ" +
                    "TFVRUN4TXdLR01wSURJd01USWdSVzUwY25WemRDd2dTVzVqTGlBdElHWnZjaUJoZFhSb2IzSnBlbVZrS" +
                    "UhWelpTQnZibXg1TVM0d0xBWURWUVFERXlWRmJuUnlkWE4wSUVObGNuUnBabWxqWVhScGIyNGdRWFYwY" +
                    "Uc5eWFYUjVJQzBnVERGTE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM" +
                    "morVzBFMjVMMFRuMnpsZW0xRHVYS1ZoMmtGblV3bXFBSnFPVjM4cGE5dkg0U0VrcWpyUWpVY2owdTF5R" +
                    "nZDUklkSmR0N2hMcUlPUHQ1RXlhTS9PSlpNc3NuMlh5UDdCdEJlNkNaNERrSk43ZkVtREltaUttOTVId" +
                    "3pHWWVpNTlRQXZTN3o3VHNveXFqMGlwL3dEb0tWZ0c5N2FUV3BSekppYXRXQTdsUXJqVjZuTjVaR2hUS" +
                    "mJpRXo1UjZyZ1pGREtOclRkREd2dW9ZcERid2tySzZISWlQT2xKLzkxNXRneHlkOEIvbHc5YmRwWGlTU" +
                    "GJCdExPckp6NVJCR1hGRWFMcEhQQVRwWGJvKzhEWDNGYmFlOGk0VkhqOUh5TWc0cDNORlhVMndPN0dPR" +
                    "nlrMzZ0MEZBU0s3bERZcWpWczEvbE1aTHdoR3dTcXpHbUlkVGl2Wkd3SURBUUFCbzRJQkREQ0NBUWd3R" +
                    "GdZRFZSMFBBUUgvQkFRREFnRUdNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUF3TXdZSUt3WUJCUVVIQ" +
                    "VFFRUp6QWxNQ01HQ0NzR0FRVUZCekFCaGhkb2RIUndPaTh2YjJOemNDNWxiblJ5ZFhOMExtNWxkREF3Q" +
                    "mdOVkhSOEVLVEFuTUNXZ0k2QWhoaDlvZEhSd09pOHZZM0pzTG1WdWRISjFjM1F1Ym1WMEwyY3lZMkV1W" +
                    "TNKc01Ec0dBMVVkSUFRME1ESXdNQVlFVlIwZ0FEQW9NQ1lHQ0NzR0FRVUZCd0lCRmhwb2RIUndPaTh2Z" +
                    "DNkM0xtVnVkSEoxYzNRdWJtVjBMM0p3WVRBZEJnTlZIUTRFRmdRVWdxSndkTjI4VXovUGU5VDN6WCtuW" +
                    "U1ZS1RMOHdId1lEVlIwakJCZ3dGb0FVYW5JbWV0QWU3MzNuTzJsUjFHeU5uNUFTWnFzd0RRWUpLb1pJa" +
                    "HZjTkFRRUxCUUFEZ2dFQkFEblZqcGlEWWNnc1k5TndIUmt3eS9ZSnJNeHAxY25jTjBIeU1nL3ZkTU5ZO" +
                    "W5nbkNUUUlsWkl2MTkrNG8vME9nZW1rbk5NL1RXZ3JGVEVLRmN4U0JKUG9rMUREMmJIaTRXaTNPZ2wwO" +
                    "FRSWUNqOTNtRUM0NW1qL1hlVElSc1hzZ2RmSmdoaGNnODV4Mkx5L3JKa0NrOXVVbUlUU25LYTEvbHk3O" +
                    "EVxdklhekNQMGtrWjlZdWpzK3N6R1FWR0hMbGJIZlRVcWk1M1kyc0FFbzFHZFJ2YzZOMTcydGt3K0NOZ" +
                    "3hLaGl1Y09oazNZdENBYnZtcWxqRXRvWnVNcngxZ0wrMVlRMUpIN0hkTXhXQkNNUk9OMWV4Q2R0VGl4O" +
                    "XFyS2dXUnM2UExpZ1ZXWFVYL2h3aWRRb3NrOFd3QkQ5bHU1MWFYOC93ZFFRR2NIc0ZYd3QzNXVMY3c9P" +
                    "C9kczpYNTA5Q2VydGlmaWNhdGU+PC9kczpYNTA5RGF0YT48ZHM6WDUwOURhdGE+PGRzOlg1MDlDZXJ0a" +
                    "WZpY2F0ZT5NSUlFL3pDQ0ErZWdBd0lCQWdJRVVkTkFSREFOQmdrcWhraUc5dzBCQVFzRkFEQ0JzREVMT" +
                    "UFrR0ExVUVCaE1DVlZNeEZqQVVCZ05WQkFvVERVVnVkSEoxYzNRc0lFbHVZeTR4T1RBM0JnTlZCQXNUT" +
                    "UhkM2R5NWxiblJ5ZFhOMExtNWxkQzlEVUZNZ2FYTWdhVzVqYjNKd2IzSmhkR1ZrSUdKNUlISmxabVZ5W" +
                    "lc1alpURWZNQjBHQTFVRUN4TVdLR01wSURJd01EWWdSVzUwY25WemRDd2dTVzVqTGpFdE1Dc0dBMVVFQ" +
                    "XhNa1JXNTBjblZ6ZENCU2IyOTBJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNU1CNFhEVEUwT" +
                    "URreU1qRTNNVFExTjFvWERUSTBNRGt5TXpBeE16RTFNMW93Z2I0eEN6QUpCZ05WQkFZVEFsVlRNUll3R" +
                    "kFZRFZRUUtFdzFGYm5SeWRYTjBMQ0JKYm1NdU1TZ3dKZ1lEVlFRTEV4OVRaV1VnZDNkM0xtVnVkSEoxY" +
                    "zNRdWJtVjBMMnhsWjJGc0xYUmxjbTF6TVRrd053WURWUVFMRXpBb1l5a2dNakF3T1NCRmJuUnlkWE4wT" +
                    "ENCSmJtTXVJQzBnWm05eUlHRjFkR2h2Y21sNlpXUWdkWE5sSUc5dWJIa3hNakF3QmdOVkJBTVRLVVZ1Z" +
                    "EhKMWMzUWdVbTl2ZENCRFpYSjBhV1pwWTJGMGFXOXVJRUYxZEdodmNtbDBlU0F0SUVjeU1JSUJJakFOQ" +
                    "mdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdW9TMmN0dWVER3ZpbWVrd0FhZDI2aks0b" +
                    "FVFYXlkcGhUbGh5ei83MmdubS9jMkVHQ3FVbjJMTmYwMFZPSEhMV1RqTHljb29QOTRNWjBHcUFnQUJGS" +
                    "HJESDU1cS9FbGNuSEtOb0x3cUh2V3ByRGw1bDh4eDMxZFNGalhBaHRMTXk1NHVpMVlZNUFyRzQwa2ZPN" +
                    "U1sSnhEdW4zdnRVZlZlKzhPaHV3bm15T2d0VjRsQ1lGaklUWEM5NFZzSENsTFB5V3VRbm1wOGsxOGJzM" +
                    "EpzbGd1UE13c1JGeFl5WGVnWnJLaEdmcVFwdVNEdHYyOVFSR1VMM2p3ZS85Vk5mbkQ3MEZ5em1hYXhPT" +
                    "Wt4aWQrcTM2T1c3Tkx3Wmk2NmNVZWUzZnJWVHNUTWk1VzNQY0R3YSt1S2JaN2FEOUkybHIySk1UZUJZc" +
                    "kdRMEVnUDR0bzJVWXlTa2NRSURBUUFCbzRJQkR6Q0NBUXN3RGdZRFZSMFBBUUgvQkFRREFnRUdNQklHQ" +
                    "TFVZEV3RUIvd1FJTUFZQkFmOENBUUV3TXdZSUt3WUJCUVVIQVFFRUp6QWxNQ01HQ0NzR0FRVUZCekFCa" +
                    "Ghkb2RIUndPaTh2YjJOemNDNWxiblJ5ZFhOMExtNWxkREF6QmdOVkhSOEVMREFxTUNpZ0pxQWtoaUpvZ" +
                    "EhSd09pOHZZM0pzTG1WdWRISjFjM1F1Ym1WMEwzSnZiM1JqWVRFdVkzSnNNRHNHQTFVZElBUTBNREl3T" +
                    "UFZRVZSMGdBREFvTUNZR0NDc0dBUVVGQndJQkZocG9kSFJ3T2k4dmQzZDNMbVZ1ZEhKMWMzUXVibVYwT" +
                    "DBOUVV6QWRCZ05WSFE0RUZnUVVhbkltZXRBZTczM25PMmxSMUd5Tm41QVNacXN3SHdZRFZSMGpCQmd3R" +
                    "m9BVWFKRGtaNlNtVTRESGhtYWs4ZmRMUS91RXZXMHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR2t6Z" +
                    "y93b2VtOTk3NTFWNjhVK2VwMTFzOHpET0RiWk5LSW9hQmpxSG1uVHZlZlFkOXE0QUlOT1NzOXYwZkhCS" +
                    "Wo5MDVQZVlTWjZidHA3aDI1aDNMVlkwc2FnODJmM0F6Y2UvQlFQVUFzWHg1Y2JhQ0tVVHgySWpFZEZoT" +
                    "UIxZ2hFWHZlYWpHSnBPa3Q4MDB1R25GRS9hUnM4bEZjM2Eya3ZaMkNsdmhBMGUzNlNsTWtUSWpOMHFjT" +
                    "mRoNC9SMGY1SU9KSklDdHQvblA1RjJsMUhIRWhWdHdIOXMvSEFIckdrVW1NUlRNWmI5bjNzck1NMlhsU" +
                    "VpIWE43NUJHcGFkNW9xWG5hZk9yRTZhUGIwQm9HclpUeUlBaTBUVmFXSjdMdXZNdXVlU2ZXbG5QZnk0Z" +
                    "k41Qmg5QnA2cm9LR0hvYWxVT3plWEVvZG0yaCsxZEs3RTNJRGhBPTwvZHM6WDUwOUNlcnRpZmljYXRlP" +
                    "jwvZHM6WDUwOURhdGE+PGRzOlg1MDlEYXRhPjxkczpYNTA5Q2VydGlmaWNhdGU+TUlJRWtUQ0NBM21nQ" +
                    "XdJQkFnSUVSV3RRVkRBTkJna3Foa2lHOXcwQkFRVUZBRENCc0RFTE1Ba0dBMVVFQmhNQ1ZWTXhGakFVQ" +
                    "mdOVkJBb1REVVZ1ZEhKMWMzUXNJRWx1WXk0eE9UQTNCZ05WQkFzVE1IZDNkeTVsYm5SeWRYTjBMbTVsZ" +
                    "EM5RFVGTWdhWE1nYVc1amIzSndiM0poZEdWa0lHSjVJSEpsWm1WeVpXNWpaVEVmTUIwR0ExVUVDeE1XS" +
                    "0dNcElESXdNRFlnUlc1MGNuVnpkQ3dnU1c1akxqRXRNQ3NHQTFVRUF4TWtSVzUwY25WemRDQlNiMjkwS" +
                    "UVObGNuUnBabWxqWVhScGIyNGdRWFYwYUc5eWFYUjVNQjRYRFRBMk1URXlOekl3TWpNME1sb1hEVEkyT" +
                    "VRFeU56SXdOVE0wTWxvd2diQXhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWURWUVFLRXcxRmJuUnlkWE4wT" +
                    "ENCSmJtTXVNVGt3TndZRFZRUUxFekIzZDNjdVpXNTBjblZ6ZEM1dVpYUXZRMUJUSUdseklHbHVZMjl5Y" +
                    "0c5eVlYUmxaQ0JpZVNCeVpXWmxjbVZ1WTJVeEh6QWRCZ05WQkFzVEZpaGpLU0F5TURBMklFVnVkSEoxY" +
                    "zNRc0lFbHVZeTR4TFRBckJnTlZCQU1USkVWdWRISjFjM1FnVW05dmRDQkRaWEowYVdacFkyRjBhVzl1S" +
                    "UVGMWRHaHZjbWwwZVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGFWd" +
                    "GtOQytzWnRLbTlJMzVSTU9WY0Y3c041RVVGb051M3MvcG9CajZFNEtQejNFRVptTGswZUdyRWFUc2JSd" +
                    "0pXSXNNbi9NWXN6QTl1M2czcytJSVJlN2JKV0tLZjQ0TGxBY1RmRnkwY09seXBvd0NLVlloWGJSOW4xM" +
                    "EN2L2drdkpyVDdlVE51UWdGQS9DWXFFQU93d0NqMFl6ZnY5S2xtYUk1VVhMRVdlSDI1RGVXME1YSmorU" +
                    "0tmRkkwZGNYdjF1NXg2MDltaEYwWWFEVzZLS2piSGpLWUQrSlhHSXJiNjhqNnhTbGt1cVVZM2tFekVaN" +
                    "kU1Tm45dXNzMnJWdkRsVWNjcDZlbitRM1gwZGdObUJ1MWttd2hIKzVwUGk5NERrWmZzME53NHBnSEJOc" +
                    "nppR0xwNS9WNitlRjY3ckhNc29JVisySE5qbm9nUWkrZFBhMk1zQ0F3RUFBYU9Cc0RDQnJUQU9CZ05WS" +
                    "FE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBckJnTlZIUkFFSkRBaWdBOHlNREEyT" +
                    "VRFeU56SXdNak0wTWxxQkR6SXdNall4TVRJM01qQTFNelF5V2pBZkJnTlZIU01FR0RBV2dCUm9rT1Juc" +
                    "EtaVGdNZUdacVR4OTB0RCs0UzliVEFkQmdOVkhRNEVGZ1FVYUpEa1o2U21VNERIaG1hazhmZExRL3VFd" +
                    "lcwd0hRWUpLb1pJaHZaOUIwRUFCQkF3RGhzSVZqY3VNVG8wTGpBREFnU1FNQTBHQ1NxR1NJYjNEUUVCQ" +
                    "lFVQUE0SUJBUUNUMURDdzF3TWdLdEQ1WStpUkRBVWdxVjhaeW50eVR0U3gyOUNXKzFSYUdTd01DUGV5d" +
                    "klXb25YOXRPMUt6S3R2bjFJU01ZL1lQeXlZQmtWQnM5RjhVNHBOMHdCT2VNRHBRNDdSZ3hSendJa1NOY" +
                    "1Vlc3lCcko2WnVhQUdBVC8zQitYeEZOU1J1ekZWSjd5VlRhdjUyVnIydWEySjdwOGVSRGplSVJSRHEvc" +
                    "jcyRFFuTlNpNnE3cHluUDlXUWNDazNSdktxc255clEvMzkvMm4zcXNlMHdKY0dFMmpUU1czaURWdXljT" +
                    "nNNbTRoSDJaMGtka3F1TSsrdi9ldTZGU3FkUWdQQ25YRXFVTGw4Rm1UeFNRZUROdEdQUEFVTzZuSVBja" +
                    "jJBNzgxcTB0SHV1Mmd1UU9IWHZnUjFtMHZkWGNEYXp2L3dvcjNFbGhWc1QvaDUvV3JRODwvZHM6WDUwO" +
                    "UNlcnRpZmljYXRlPjwvZHM6WDUwOURhdGE+PC9kczpLZXlJbmZvPjwvZHM6U2lnbmF0dXJlPjxzYW1sM" +
                    "jpTdWJqZWN0PjxzYW1sMjpOYW1lSUQgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoxLjE6b" +
                    "mFtZWlkLWZvcm1hdDpXaW5kb3dzRG9tYWluUXVhbGlmaWVkTmFtZSIgTmFtZVF1YWxpZmllcj0id2FjL" +
                    "mRhcy5teWF0b3MubmV0Ij5BNjQ3MjQ1PC9zYW1sMjpOYW1lSUQ+PHNhbWwyOlN1YmplY3RDb25maXJtY" +
                    "XRpb24gTWV0aG9kPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6Y206YmVhcmVyIj48c2FtbDI6U" +
                    "3ViamVjdENvbmZpcm1hdGlvbkRhdGEgSW5SZXNwb25zZVRvPSJfMWQ1NmVmNmY1NGE5MDY0ZWE1NjUxN" +
                    "DllMWUzNjA1NDQiIE5vdE9uT3JBZnRlcj0iMjAxOC0wOC0yN1QwNzo1NzowNi42MjNaIiBSZWNpcGllb" +
                    "nQ9Imh0dHBzOi8vdXJhLWFhLml0LXNvbHV0aW9ucy5hdG9zLm5ldC9kYW5hLW5hL2F1dGgvc2FtbC1jb" +
                    "25zdW1lci5jZ2kiLz48L3NhbWwyOlN1YmplY3RDb25maXJtYXRpb24+PC9zYW1sMjpTdWJqZWN0PjxzY" +
                    "W1sMjpDb25kaXRpb25zIE5vdEJlZm9yZT0iMjAxOC0wOC0yN1QwNzo1MjowNi42MjNaIiBOb3RPbk9yQ" +
                    "WZ0ZXI9IjIwMTgtMDgtMjdUMDc6NTc6MDYuNjIzWiI+PHNhbWwyOkF1ZGllbmNlUmVzdHJpY3Rpb24+P" +
                    "HNhbWwyOkF1ZGllbmNlPmh0dHBzOi8vdXJhLWFhLml0LXNvbHV0aW9ucy5hdG9zLm5ldC9kYW5hLW5hL" +
                    "2F1dGgvc2FtbC1lbmRwb2ludC5jZ2k/cD1zcDE8L3NhbWwyOkF1ZGllbmNlPjwvc2FtbDI6QXVkaWVuY" +
                    "2VSZXN0cmljdGlvbj48L3NhbWwyOkNvbmRpdGlvbnM+PHNhbWwyOkF1dGhuU3RhdGVtZW50IEF1dGhuS" +
                    "W5zdGFudD0iMjAxOC0wOC0yN1QwNzo1MjozNS41MzBaIiBTZXNzaW9uSW5kZXg9InV1aWQtOWQ2MzNiN" +
                    "DktZTE2NC00ZTIyLWJhNGYtOWMzYzFiYjQyNzc2Ij48c2FtbDI6QXV0aG5Db250ZXh0PjxzYW1sMjpBd" +
                    "XRobkNvbnRleHRDbGFzc1JlZj51cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YWM6Y2xhc3NlczpYN" +
                    "TA5PC9zYW1sMjpBdXRobkNvbnRleHRDbGFzc1JlZj48L3NhbWwyOkF1dGhuQ29udGV4dD48L3NhbWwyO" +
                    "kF1dGhuU3RhdGVtZW50Pjwvc2FtbDI6QXNzZXJ0aW9uPjwvc2FtbDJwOlJlc3BvbnNlPg==");
            request6Body.FormPostParameters.Add("RelayState", "https://ura-aa.it-solutions.atos.net/ura-sso");
            request6.Body = request6Body;
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("https://ura-aa.it-solutions.atos.net/dana-na/html/blank.html");
            request7.ThinkTime = 2;
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("https://ura-aa.it-solutions.atos.net/dana-na/auth/url_14/welcome.cgi");
            request8.ThinkTime = 35;
            request8.QueryStringParameters.Add("p", "preauth", false, false);
            request8.QueryStringParameters.Add("id", "state_2e628e7abeaa2fca1a9908338dfcb00f", false, false);
            request8.QueryStringParameters.Add("signinRealmId", "18", false, false);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("https://ura-aa.it-solutions.atos.net/dana-na/auth/setcookie.cgi");
            request9.ThinkTime = 2;
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("https://ura-aa.it-solutions.atos.net/dana/home/starter0.cgi");
            request10.ThinkTime = 1;
            request10.ExpectedResponseUrl = "https://ura-aa.it-solutions.atos.net/dana/home/starter.cgi";
            FormPostHttpBody request10Body = new FormPostHttpBody();
            request10Body.FormPostParameters.Add("xsauth", "3187b4c9da041bcc5a9a89f4f25f87d4");
            request10Body.FormPostParameters.Add("tz_offset", "330");
            request10Body.FormPostParameters.Add("clienttime", "1535356403");
            request10Body.FormPostParameters.Add("url", "");
            request10Body.FormPostParameters.Add("activex_enabled", "1");
            request10Body.FormPostParameters.Add("java_enabled", "0");
            request10Body.FormPostParameters.Add("power_user", "0");
            request10Body.FormPostParameters.Add("grab", "1");
            request10Body.FormPostParameters.Add("browserproxy", "");
            request10Body.FormPostParameters.Add("browsertype", "");
            request10Body.FormPostParameters.Add("browserproxysettings", "");
            request10Body.FormPostParameters.Add("check", "yes");
            request10.Body = request10Body;
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("https://ura-aa.it-solutions.atos.net/dana/home/index.cgi");
            request11.ThinkTime = 7;
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("https://ura-aa.it-solutions.atos.net/dana/nc/ncrun.cgi");
            request12.ThinkTime = 22;
            request12.QueryStringParameters.Add("launch_nc", "1", false, false);
            request12.QueryStringParameters.Add("psalapp", "nc", false, false);
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("https://ura-aa.it-solutions.atos.net/dana-na/auth/rd.cgi");
            request13.ExpectedResponseUrl = "https://ura-aa.it-solutions.atos.net/dana/home/index.cgi";
            FormPostHttpBody request13Body = new FormPostHttpBody();
            request13Body.FormPostParameters.Add("DSPSALPREF", "7q2DWxznDAABAAAA0CSVQVMIxzfwk4D0pNdy2gLxNHQde2er/Pnxh9wd7Eo=");
            request13Body.FormPostParameters.Add("DSSignInURL", "/ura-sso");
            request13Body.FormPostParameters.Add("DSFirstAccess", "1535356397");
            request13Body.FormPostParameters.Add("DSSIGNIN", "url_14");
            request13Body.FormPostParameters.Add("DSLastAccess", "1535356410");
            request13Body.FormPostParameters.Add("DSID", "9949adbf4925ad4bd48e110a4a6899cd");
            request13Body.FormPostParameters.Add("FIDM_Locale", "en_US");
            request13.Body = request13Body;
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("https://www.msn.com/spartan/ientp");
            request14.ThinkTime = 1;
            request14.QueryStringParameters.Add("locale", "en-IN", false, false);
            request14.QueryStringParameters.Add("market", "IN", false, false);
            request14.QueryStringParameters.Add("enableregulatorypsm", "0", false, false);
            request14.QueryStringParameters.Add("NTLogo", "1", false, false);
            request14.QueryStringParameters.Add("IsFRE", "0", false, false);
            WebTestRequest request14Dependent1 = new WebTestRequest("https://static-spartan-eas-s-msn-com.akamaized.net/sc/48/a7b61d.woff");
            request14Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request14.DependentRequests.Add(request14Dependent1);
            WebTestRequest request14Dependent2 = new WebTestRequest("https://static-spartan-eas-s-msn-com.akamaized.net/sc/92/d675c4.woff");
            request14Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request14.DependentRequests.Add(request14Dependent2);
            WebTestRequest request14Dependent3 = new WebTestRequest("https://www.msn.com/spartan/en-sg/ientpajax");
            request14Dependent3.Headers.Add(new WebTestRequestHeader("Content-Type", "html"));
            request14Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request14Dependent3.QueryStringParameters.Add("market", "IN", false, false);
            request14Dependent3.QueryStringParameters.Add("enableregulatorypsm", "0", false, false);
            request14Dependent3.QueryStringParameters.Add("NTLogo", "1", false, false);
            request14Dependent3.QueryStringParameters.Add("IsFRE", "0", false, false);
            request14Dependent3.QueryStringParameters.Add("appslocale", "en-sg", false, false);
            request14Dependent3.QueryStringParameters.Add("telemetrystartindex", "78", false, false);
            request14Dependent3.QueryStringParameters.Add("telemetryparentindex", "8", false, false);
            request14Dependent3.QueryStringParameters.Add("telemetryordinalstartindex", "11", false, false);
            request14Dependent3.QueryStringParameters.Add("ou", "https%3A%2F%2Fwww.msn.com%2Fspartan%2Fientp%3Flocale%3Den-IN%26market%3DIN%26enab" +
                    "leregulatorypsm%3D0%26NTLogo%3D1%26IsFRE%3D0", false, false);
            request14.DependentRequests.Add(request14Dependent3);
            WebTestRequest request14Dependent4 = new WebTestRequest(@"https://static-spartan-eas-s-msn-com.akamaized.net/spartan/en-sg/_sc/css/738b926b-5440b54e/direction=ltr.locales=en-sg.themes=start.dpi=resolution1x/98-fb481a-68ddb2ab/4b-a6fb1f-dbc6220a/c3-d6aef9-3e1618a0/d7-2b2540-af0c47b8/fd-f95300-61bd64fa/80-37c25e-68ddb2ab/34-55a04d-bc4ef775/7e-3582c9-542a5cb1/1d-b3f861-1f420d19/e3-10d406-68ddb2ab/37-19193f-d536e331/6b-0550c8-48f01c4");
            request14Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request14Dependent4.QueryStringParameters.Add("ver", "20180822_11430126", false, false);
            request14Dependent4.QueryStringParameters.Add("fdhead", "muidflt13cf,muidflt258cf,muidflt315cf,bingmsncombined1cf,pneedge1cf,starthp3cf,pl" +
                    "atagyhp3cf,audexhp3cf,artgly4cf,artgly5cf", false, false);
            request14Dependent4.QueryStringParameters.Add("csopd", "20180813170416", false, false);
            request14Dependent4.QueryStringParameters.Add("csopdb", "20180823063006", false, false);
            request14.DependentRequests.Add(request14Dependent4);
            WebTestRequest request14Dependent5 = new WebTestRequest(@"https://static-spartan-eas-s-msn-com.akamaized.net/spartan/en-sg/_sc/js/738b926b-9a38d939/direction=ltr.locales=en-sg.themes=start.dpi=resolution1x/df-2bd616-68ddb2ab/67-3465c4-68ddb2ab/3b-6cf0be-6231cc9f/d8-212070-a89c49f2/aa-3ef1e0-68ddb2ab/c1-f16ae6-68ddb2ab/7b-a584c6-630d2a11/ab-204c08-68ddb2ab/8f-5ed6a9-68ddb2ab/9f-1f1878-5599dabd");
            request14Dependent5.ThinkTime = 1;
            request14Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request14Dependent5.QueryStringParameters.Add("ver", "20180822_11430126", false, false);
            request14Dependent5.QueryStringParameters.Add("fdhead", "muidflt13cf,muidflt258cf,muidflt315cf,bingmsncombined1cf,pneedge1cf,starthp3cf,pl" +
                    "atagyhp3cf,audexhp3cf,artgly4cf,artgly5cf", false, false);
            request14Dependent5.QueryStringParameters.Add("csopd", "20180813170416", false, false);
            request14Dependent5.QueryStringParameters.Add("csopdb", "20180823063006", false, false);
            request14.DependentRequests.Add(request14Dependent5);
            WebTestRequest request14Dependent6 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request14Dependent6.ExpectedResponseUrl = "https://api.bing.com/qsml.aspx?query=a&maxwidth=32765&rowheight=20&sectionHeight=" +
                "160&FORM=IENSD2&market=en-AU";
            request14Dependent6.QueryStringParameters.Add("query", "a", false, false);
            request14Dependent6.QueryStringParameters.Add("maxwidth", "32765", false, false);
            request14Dependent6.QueryStringParameters.Add("rowheight", "20", false, false);
            request14Dependent6.QueryStringParameters.Add("sectionHeight", "160", false, false);
            request14Dependent6.QueryStringParameters.Add("FORM", "IENSD2", false, false);
            request14Dependent6.QueryStringParameters.Add("market", "en-AU", false, false);
            request14.DependentRequests.Add(request14Dependent6);
            WebTestRequest request14Dependent7 = new WebTestRequest("https://www.bing.com/profile/history/data");
            request14Dependent7.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request14Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request14Dependent7.QueryStringParameters.Add("_", "1535356469863", false, false);
            request14.DependentRequests.Add(request14Dependent7);
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request14.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("https://login.live.com/login.srf");
            request15.ExpectedResponseUrl = "https://www.msn.com/spartan/en-sg/secure/silentpassport?secure=true&lc=18441";
            request15.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request15.QueryStringParameters.Add("wa", "wsignin1.0", false, false);
            request15.QueryStringParameters.Add("rpsnv", "13", false, false);
            request15.QueryStringParameters.Add("checkda", "1", false, false);
            request15.QueryStringParameters.Add("ct", "1535356459", false, false);
            request15.QueryStringParameters.Add("rver", "7.0.6730.0", false, false);
            request15.QueryStringParameters.Add("wp", "LBI", false, false);
            request15.QueryStringParameters.Add("wreply", "https%3a%2f%2fwww.msn.com%2fspartan%2fen-sg%2fsecure%2fsilentpassport%3fsecure%3d" +
                    "true", false, false);
            request15.QueryStringParameters.Add("lc", "1033", false, false);
            request15.QueryStringParameters.Add("id", "1184", false, false);
            request15.QueryStringParameters.Add("mkt", this.Context["$HIDDEN1.mkt"].ToString(), false, false);
            WebTestRequest request15Dependent1 = new WebTestRequest("https://sam.msn.com/promotions/getSessionResult");
            request15Dependent1.Method = "OPTIONS";
            request15Dependent1.QueryStringParameters.Add("locale", "en-sg", false, false);
            request15Dependent1.QueryStringParameters.Add("v", "2", false, false);
            request15Dependent1.QueryStringParameters.Add("skipsessioncall", "false", false, false);
            request15.DependentRequests.Add(request15Dependent1);
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("https://www.msn.com/spartan/en-sg/kernel/appcache/cache.appcache");
            request16.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request16.QueryStringParameters.Add("locale", "en-in", false, false);
            request16.QueryStringParameters.Add("market", "in", false, false);
            request16.QueryStringParameters.Add("enableregulatorypsm", "0", false, false);
            request16.QueryStringParameters.Add("ntlogo", "1", false, false);
            request16.QueryStringParameters.Add("isfre", "0", false, false);
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("https://static-spartan-eas-s-msn-com.akamaized.net/spartan/en-sg/_sc/js/738b926b-" +
                    "49ad39b7/direction=ltr.locales=en-sg.themes=start.dpi=resolution1x/ed-a54651-429" +
                    "ff026");
            request17.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request17.QueryStringParameters.Add("ver", "20180822_11430126", false, false);
            request17.QueryStringParameters.Add("fdhead", "muidflt13cf,muidflt258cf,muidflt315cf,bingmsncombined1cf,pneedge1cf,starthp3cf,pl" +
                    "atagyhp3cf,audexhp3cf,artgly4cf,artgly5cf", false, false);
            request17.QueryStringParameters.Add("csopd", "20180813170416", false, false);
            request17.QueryStringParameters.Add("csopdb", "20180823063006", false, false);
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("https://otf.msn.com/c.gif");
            request18.Method = "OPTIONS";
            request18.QueryStringParameters.Add("", "", false, false);
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("https://otf.msn.com/c.gif");
            request19.Method = "OPTIONS";
            request19.QueryStringParameters.Add("", "", false, false);
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("https://otf.msn.com/c.gif");
            request20.Method = "OPTIONS";
            request20.QueryStringParameters.Add("", "", false, false);
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("https://otf.msn.com/c.gif");
            request21.Method = "OPTIONS";
            request21.QueryStringParameters.Add("", "", false, false);
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("https://www.msn.com/spartan/ientp");
            request22.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request22.QueryStringParameters.Add("locale", "en-IN", false, false);
            request22.QueryStringParameters.Add("market", "IN", false, false);
            request22.QueryStringParameters.Add("enableregulatorypsm", "0", false, false);
            request22.QueryStringParameters.Add("NTLogo", "1", false, false);
            request22.QueryStringParameters.Add("IsFRE", "0", false, false);
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("https://otf.msn.com/c.gif");
            request23.Method = "POST";
            request23.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request23.QueryStringParameters.Add("", "", false, false);
            StringHttpBody request23Body = new StringHttpBody();
            request23Body.ContentType = "application/json; charset=utf-8";
            request23Body.InsertByteOrderMark = false;
            request23Body.BodyString = "[{\"evt\":\"impr_update\",\"rid\":\"1824620c370248409d7e692f365c7ed1\",\"di\":\"17\",\"clid\":\"" +
                "17BC2008E51A620626012C50E4916347\",\"issso\":0,\"pg.p\":\"ieext\",\"pg.t\":\"ntp\",\"pg.n\":\"" +
                "default\",\"pg.c\":11,\"mech\":\"load\",\"winht\":728,\"docht\":3430,\"scrollOff\":0,\"wbh\":0," +
                "\"e1\":{\"e\":[{\"i\":1,\"n\":\"header\",\"y\":6},{\"i\":2,\"p\":1,\"n\":\"headersearch\",\"y\":9,\"o\":" +
                "1},{\"i\":3,\"p\":2,\"n\":\"searchinput\",\"y\":9,\"o\":1},{\"i\":4,\"p\":2,\"n\":\"search_websearc" +
                "h\",\"y\":9,\"o\":2},{\"i\":6,\"p\":1,\"n\":\"header-signin\",\"t\":\"signin\",\"o\":2},{\"i\":7,\"p\":" +
                "6,\"n\":\"SignInNavigation\",\"y\":14,\"o\":1},{\"i\":8,\"n\":\"main\",\"y\":6},{\"i\":9,\"p\":8,\"n\"" +
                ":\"topsites\",\"y\":8,\"o\":1},{\"i\":10,\"p\":9,\"n\":\"section_header\",\"y\":8,\"o\":1},{\"i\":11" +
                ",\"p\":10,\"n\":\"show_customize\",\"y\":14,\"o\":1},{\"i\":12,\"p\":9,\"n\":\"curated_topsite_ti" +
                "le\",\"y\":8,\"o\":2},{\"i\":13,\"p\":12,\"n\":\"curated_topsite_url\",\"y\":14,\"o\":1},{\"i\":14," +
                "\"p\":12,\"n\":\"curated_topsite_remove\",\"y\":11,\"o\":2},{\"i\":15,\"p\":12,\"n\":\"topsite_ad" +
                "d\",\"y\":11,\"o\":3},{\"i\":16,\"p\":9,\"n\":\"curated_topsite_tile\",\"y\":8,\"o\":3},{\"i\":17,\"" +
                "p\":16,\"n\":\"curated_topsite_url\",\"y\":14,\"o\":1},{\"i\":18,\"p\":16,\"n\":\"curated_topsit" +
                "e_remove\",\"y\":11,\"o\":2},{\"i\":19,\"p\":16,\"n\":\"topsite_add\",\"y\":11,\"o\":3},{\"i\":20,\"" +
                "p\":9,\"n\":\"curated_topsite_tile\",\"y\":8,\"o\":4},{\"i\":21,\"p\":20,\"n\":\"curated_topsite" +
                "_url\",\"y\":14,\"o\":1},{\"i\":22,\"p\":20,\"n\":\"curated_topsite_remove\",\"y\":11,\"o\":2},{\"" +
                "i\":23,\"p\":20,\"n\":\"topsite_add\",\"y\":11,\"o\":3},{\"i\":24,\"p\":9,\"n\":\"curated_topsite_" +
                "tile\",\"y\":8,\"o\":5},{\"i\":25,\"p\":24,\"n\":\"curated_topsite_url\",\"y\":14,\"o\":1},{\"i\":2" +
                "6,\"p\":24,\"n\":\"curated_topsite_remove\",\"y\":11,\"o\":2},{\"i\":27,\"p\":24,\"n\":\"topsite_" +
                "add\",\"y\":11,\"o\":3},{\"i\":28,\"p\":9,\"n\":\"curated_topsite_tile\",\"y\":8,\"o\":6,\"l\":\"Mic" +
                "rosoft.BingNews_8wekyb3d8bbwe!AppexNews\"},{\"i\":29,\"p\":28,\"n\":\"curated_topsite_ur" +
                "l\",\"y\":14,\"o\":1,\"l\":\"Microsoft.BingNews_8wekyb3d8bbwe!AppexNews\"},{\"i\":30,\"p\":28" +
                ",\"n\":\"curated_topsite_remove\",\"y\":11,\"o\":2,\"l\":\"Microsoft.BingNews_8wekyb3d8bbwe" +
                "!AppexNews\"},{\"i\":31,\"p\":28,\"n\":\"topsite_add\",\"y\":11,\"o\":3},{\"i\":32,\"p\":9,\"n\":\"c" +
                "urated_topsite_tile\",\"y\":8,\"o\":7},{\"i\":33,\"p\":32,\"n\":\"curated_topsite_url\",\"y\":1" +
                "4,\"o\":1},{\"i\":34,\"p\":32,\"n\":\"curated_topsite_remove\",\"y\":11,\"o\":2},{\"i\":35,\"p\":3" +
                "2,\"n\":\"topsite_add\",\"y\":11,\"o\":3},{\"i\":36,\"p\":9,\"n\":\"topsite_tile\",\"y\":8,\"o\":8}," +
                "{\"i\":39,\"p\":36,\"n\":\"topsite_add\",\"y\":11,\"o\":3},{\"i\":40,\"p\":9,\"n\":\"topsite_tile\"," +
                "\"y\":8,\"o\":9},{\"i\":43,\"p\":40,\"n\":\"topsite_add\",\"y\":11,\"o\":3},{\"i\":44,\"p\":9,\"n\":\"t" +
                "opsite_add_dialog\",\"y\":8,\"o\":10},{\"i\":45,\"p\":44,\"n\":\"user_input\",\"y\":12,\"o\":1},{" +
                "\"i\":46,\"p\":44,\"n\":\"topsite_add_dialog_save\",\"y\":11,\"o\":2},{\"i\":47,\"p\":44,\"n\":\"to" +
                "psite_add_dialog_close\",\"y\":11,\"o\":3},{\"i\":68,\"p\":8,\"n\":\"coachmark_module\",\"y\":8" +
                ",\"o\":5},{\"i\":69,\"p\":68,\"n\":\"coachmark_close\",\"y\":11,\"o\":1},{\"i\":79,\"p\":8,\"n\":\"se" +
                "ction_header\",\"y\":6,\"o\":11},{\"i\":80,\"p\":79,\"n\":\"oneriver.myfeed\",\"t\":\"oneriver.m" +
                "yfeed\",\"o\":1},{\"i\":81,\"p\":8,\"n\":\"infopane\",\"t\":\"oneriver.infopane.module\",\"o\":12" +
                "},{\"i\":82,\"p\":81,\"n\":\"single\",\"y\":13,\"o\":1},{\"i\":83,\"p\":82,\"n\":\"single\",\"y\":13,\"" +
                "l\":\"BBMujRP\",\"h\":0,\"v\":\"news\",\"c\":\"newssingapore\",\"o\":1},{\"i\":84,\"p\":81,\"n\":\"sin" +
                "gle\",\"y\":13,\"o\":2},{\"i\":85,\"p\":84,\"n\":\"single\",\"y\":13,\"l\":\"BBMup61\",\"h\":0,\"v\":\"n" +
                "ews\",\"c\":\"newsnational\",\"o\":1},{\"i\":101,\"p\":81,\"n\":\"single\",\"y\":13,\"o\":9},{\"i\":1" +
                "02,\"p\":101,\"n\":\"single\",\"y\":13,\"l\":\"BBMuulI\",\"h\":0,\"v\":\"entertainment\",\"c\":\"cele" +
                "brity\",\"o\":1},{\"n\":\"previousSlideArrow\",\"y\":12,\"i\":142,\"o\":2,\"p\":\"81\"},{\"n\":\"nex" +
                "tSlideArrow\",\"y\":12,\"i\":143,\"o\":3,\"p\":\"81\"},{\"i\":103,\"p\":8,\"n\":\"river_content\",\"" +
                "y\":8,\"o\":13},{\"i\":104,\"p\":103,\"n\":\"RiverCardPhotoLarge\",\"y\":13,\"l\":\"BBMubKE\",\"h\"" +
                ":0,\"v\":\"lifestyle\",\"c\":\"lifestylehealth\",\"o\":1},{\"i\":105,\"p\":104,\"n\":\"kicker\",\"y" +
                "\":14,\"o\":1},{\"i\":138,\"p\":8,\"n\":\"floatingfeedback\",\"y\":11,\"o\":14}]},\"tmpl\":\"IP:No" +
                "ne;RV:None;infopane:0;cat:0;EP:0;CI:1;spartanExternalContentModule:1\",\"mkt\":\"en-" +
                "sg\",\"flightid\":\"muidflt13cf,muidflt258cf,muidflt315cf,bingmsncombined1cf,pneedge" +
                "1cf,starthp3cf,platagyhp3cf,audexhp3cf,artgly4cf,artgly5cf\",\"idx\":4}]";
            request23.Body = request23Body;
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("https://otf.msn.com/c.gif");
            request24.Method = "POST";
            request24.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request24.QueryStringParameters.Add("", "", false, false);
            StringHttpBody request24Body = new StringHttpBody();
            request24Body.ContentType = "application/json; charset=utf-8";
            request24Body.InsertByteOrderMark = false;
            request24Body.BodyString = @"[{""evt"":""impr_update"",""rid"":""1824620c370248409d7e692f365c7ed1"",""di"":""17"",""clid"":""17BC2008E51A620626012C50E4916347"",""issso"":0,""pg.p"":""ieext"",""pg.t"":""ntp"",""pg.n"":""default"",""pg.c"":11,""mech"":""partial"",""winht"":728,""docht"":3430,""scrollOff"":0,""wbh"":0,""e1"":{""e"":[{""n"":""previousSlideArrow"",""y"":12,""i"":142,""o"":2,""p"":""81""}]},""tmpl"":""IP:None;RV:None;infopane:0;cat:0;EP:0;CI:1;spartanExternalContentModule:1"",""mkt"":""en-sg"",""flightid"":""muidflt13cf,muidflt258cf,muidflt315cf,bingmsncombined1cf,pneedge1cf,starthp3cf,platagyhp3cf,audexhp3cf,artgly4cf,artgly5cf"",""idx"":2}]";
            request24.Body = request24Body;
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("https://otf.msn.com/c.gif");
            request25.Method = "POST";
            request25.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request25.QueryStringParameters.Add("", "", false, false);
            StringHttpBody request25Body = new StringHttpBody();
            request25Body.ContentType = "application/json; charset=utf-8";
            request25Body.InsertByteOrderMark = false;
            request25Body.BodyString = @"[{""evt"":""load_time"",""rid"":""1824620c370248409d7e692f365c7ed1"",""di"":""17"",""clid"":""17BC2008E51A620626012C50E4916347"",""issso"":0,""pg.p"":""ieext"",""pg.t"":""ntp"",""pg.n"":""default"",""pg.c"":11,""markers"":{""TTTS"":9723,""TTAFAnimation"":16163,""TTAF"":19054,""TTAFImgs"":19983,""TTAFAndImgs"":19983,""TTAFMax"":19983,""TFPR"":19983,""TTAFImgInfopane"":20005},""idx"":5}]";
            request25.Body = request25Body;
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("https://otf.msn.com/c.gif");
            request26.Method = "POST";
            request26.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request26.QueryStringParameters.Add("", "", false, false);
            StringHttpBody request26Body = new StringHttpBody();
            request26Body.ContentType = "application/json; charset=utf-8";
            request26Body.InsertByteOrderMark = false;
            request26Body.BodyString = @"[{""evt"":""impr_update"",""rid"":""1824620c370248409d7e692f365c7ed1"",""di"":""17"",""clid"":""17BC2008E51A620626012C50E4916347"",""issso"":0,""pg.p"":""ieext"",""pg.t"":""ntp"",""pg.n"":""default"",""pg.c"":11,""mech"":""partial"",""winht"":728,""docht"":3430,""scrollOff"":0,""wbh"":0,""e1"":{""e"":[{""n"":""nextSlideArrow"",""y"":12,""i"":143,""o"":3,""p"":""81""}]},""tmpl"":""IP:None;RV:None;infopane:0;cat:0;EP:0;CI:1;spartanExternalContentModule:1"",""mkt"":""en-sg"",""flightid"":""muidflt13cf,muidflt258cf,muidflt315cf,bingmsncombined1cf,pneedge1cf,starthp3cf,platagyhp3cf,audexhp3cf,artgly4cf,artgly5cf"",""idx"":3}]";
            request26.Body = request26Body;
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("https://www.msn.com/spartan/en-sg/kernel/appcache/cache.appcache");
            request27.ThinkTime = 2;
            request27.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request27.QueryStringParameters.Add("locale", "en-in", false, false);
            request27.QueryStringParameters.Add("market", "in", false, false);
            request27.QueryStringParameters.Add("enableregulatorypsm", "0", false, false);
            request27.QueryStringParameters.Add("ntlogo", "1", false, false);
            request27.QueryStringParameters.Add("isfre", "0", false, false);
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("https://otf.msn.com/c.gif");
            request28.ThinkTime = 42;
            request28.Method = "POST";
            request28.Headers.Add(new WebTestRequestHeader("Referer", "https://www.msn.com/spartan/ientp?locale=en-IN&market=IN&enableregulatorypsm=0&NT" +
                        "Logo=1&IsFRE=0"));
            request28.QueryStringParameters.Add("", "", false, false);
            StringHttpBody request28Body = new StringHttpBody();
            request28Body.ContentType = "application/json; charset=utf-8";
            request28Body.InsertByteOrderMark = false;
            request28Body.BodyString = @"[{""evt"":""impr_update"",""rid"":""1824620c370248409d7e692f365c7ed1"",""di"":""17"",""clid"":""17BC2008E51A620626012C50E4916347"",""issso"":0,""pg.p"":""ieext"",""pg.t"":""ntp"",""pg.n"":""default"",""pg.c"":11,""mech"":""auto"",""winht"":728,""docht"":3430,""scrollOff"":0,""wbh"":0,""e1"":{""e"":[{""i"":84,""p"":81,""n"":""single"",""y"":13,""o"":2},{""i"":85,""p"":84,""n"":""single"",""y"":13,""l"":""BBMup61"",""h"":0,""v"":""news"",""c"":""newsnational"",""o"":1}]},""tmpl"":""IP:None;RV:None;infopane:0;cat:0;EP:0;CI:1;spartanExternalContentModule:1"",""mkt"":""en-sg"",""flightid"":""muidflt13cf,muidflt258cf,muidflt315cf,bingmsncombined1cf,pneedge1cf,starthp3cf,platagyhp3cf,audexhp3cf,artgly4cf,artgly5cf"",""idx"":6}]";
            request28.Body = request28Body;
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("https://fidm.access.it-solutions.atos.net/auth/Login");
            request29.ThinkTime = 4;
            request29.QueryStringParameters.Add("GASF", "CERTIFICATE", false, false);
            request29.QueryStringParameters.Add("GAREASONCODE", "-1", false, false);
            request29.QueryStringParameters.Add("GARESOURCEID", "ga^default^global^resource", false, false);
            request29.QueryStringParameters.Add("GAURI", "https://fidm.access.it%2Dsolutions.atos.net/GetAccess/Pmda%3FMDURI%3DaHR0cHM6Ly9h" +
                    "ZG1pbmdhdGUtZW1lYS5zYWFjb24ubmV0L0NpdHJpeC9YZW5BcHAvYXV0aC9sb2dpbi5hc3B4%26SD%3D" +
                    ".saacon.net%26GARESOURCEID%3DAdmingateEmeaSaaconNet2%26APPID%3DAdmingateEmeaSaac" +
                    "onNet2", false, false);
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("https://fidm.access.it-solutions.atos.net/auth/Login");
            request30.ExpectedResponseUrl = "https://fidm.access.it-solutions.atos.net/GetAccess/Pmda?MDURI=aHR0cHM6Ly9hZG1pbm" +
                "dhdGUtZW1lYS5zYWFjb24ubmV0L0NpdHJpeC9YZW5BcHAvYXV0aC9sb2dpbi5hc3B4&SD=.saacon.ne" +
                "t&GARESOURCEID=AdmingateEmeaSaaconNet2&APPID=AdmingateEmeaSaaconNet2";
            FormPostHttpBody request30Body = new FormPostHttpBody();
            request30Body.FormPostParameters.Add("AUTHMETHOD", "CERTIFICATE");
            request30Body.FormPostParameters.Add("Template", "AtosPkiOnly");
            request30Body.FormPostParameters.Add("HiddenURI", "https://fidm.access.it%2Dsolutions.atos.net/GetAccess/Pmda%3FMDURI%3DaHR0cHM6Ly9h" +
                    "ZG1pbmdhdGUtZW1lYS5zYWFjb24ubmV0L0NpdHJpeC9YZW5BcHAvYXV0aC9sb2dpbi5hc3B4%26SD%3D" +
                    ".saacon.net%26GARESOURCEID%3DAdmingateEmeaSaaconNet2%26APPID%3DAdmingateEmeaSaac" +
                    "onNet2");
            request30Body.FormPostParameters.Add("GARESOURCEID", "ga^default^global^resource");
            request30Body.FormPostParameters.Add("GASF", "CERTIFICATE");
            request30Body.FormPostParameters.Add("pageGenTime", "1535356480253");
            request30Body.FormPostParameters.Add("LOCALE", "en_US");
            request30Body.FormPostParameters.Add("PKI_LOGIN", "Login");
            request30Body.FormPostParameters.Add("CSRFToken", "$CSRFToken");
            request30Body.FormPostParameters.Add("CSRFFormToken", "d8e26297e549f5d2cf52834d04e82606ef4637f571675b59");
            request30.Body = request30Body;
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("https://cp-fidm.saacon.net/GetAccess/Smda");
            request31.Encoding = System.Text.Encoding.GetEncoding("Windows-1252");
            request31.ExpectedResponseUrl = "https://admingate-emea.saacon.net/Citrix/XenApp/auth/silentDetection.aspx";
            request31.QueryStringParameters.Add("MDURI", "aHR0cHM6Ly9hZG1pbmdhdGUtZW1lYS5zYWFjb24ubmV0L0NpdHJpeC9YZW5BcHAvYXV0aC9sb2dpbi5hc" +
                    "3B4", false, false);
            FormPostHttpBody request31Body = new FormPostHttpBody();
            request31Body.FormPostParameters.Add("FIDM_AUTH_SESSION_ID", "SMS_defthw990chweb_10c5b7::4b238ec0112358f53ae4adc380418ebe");
            request31Body.FormPostParameters.Add("CSRFFormToken", "4e95f70d4210678db548bf176108c308831802cfc100280a");
            request31.Body = request31Body;
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("https://admingate-emea.saacon.net/Citrix/XenApp/auth/silentDetection.aspx");
            request32.ThinkTime = 3;
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("https://admingate-emea.saacon.net/Citrix/XenApp/auth/clientDetectionOutputs.aspx");
            request33.ThinkTime = 2;
            request33.ExpectedResponseUrl = "https://admingate-emea.saacon.net/Citrix/XenApp/auth/silentDetection.aspx";
            FormPostHttpBody request33Body = new FormPostHttpBody();
            request33Body.FormPostParameters.Add("SESSION_TOKEN", "5981BE6EABA4F2603F83576BEBEEFB36");
            request33Body.FormPostParameters.Add("RemoteClient", "Ica-Local=Auto");
            request33Body.FormPostParameters.Add("StreamingClient", "");
            request33Body.FormPostParameters.Add("IcoStatus", "IsNotPassthrough");
            request33.Body = request33Body;
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("https://admingate-emea.saacon.net/Citrix/XenApp/auth/login.aspx");
            request34.ThinkTime = 2;
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("https://admingate-emea.saacon.net/Citrix/XenApp/html/dummy.html");
            request35.ThinkTime = 62;
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("https://admingate-emea.saacon.net/Citrix/XenApp/auth/login.aspx");
            request36.ThinkTime = 12;
            request36.ExpectedResponseUrl = "https://admingate-emea.saacon.net/Citrix/XenApp/site/default.aspx";
            FormPostHttpBody request36Body = new FormPostHttpBody();
            request36Body.FormPostParameters.Add("SESSION_TOKEN", "5981BE6EABA4F2603F83576BEBEEFB36");
            request36Body.FormPostParameters.Add("LoginType", "Explicit");
            request36Body.FormPostParameters.Add("user", "a647245");
            request36Body.FormPostParameters.Add("password", "December@25032003");
            request36Body.FormPostParameters.Add("domain", "saacon");
            request36.Body = request36Body;
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest("https://admingate-emea.saacon.net/Citrix/XenApp/html/dummy.html");
            request37.ThinkTime = 13;
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("https://admingate-emea.saacon.net/Citrix/XenApp/site/launcher.aspx");
            request38.QueryStringParameters.Add("CTX_Application", "Citrix.MPS.App.AdmingateSaaconV2.BMW%20Europe%20Farm%20managed%20by%20customer_DE" +
                    "", false, false);
            request38.QueryStringParameters.Add("CTX_Token", "5981BE6EABA4F2603F83576BEBEEFB36", false, false);
            request38.QueryStringParameters.Add("LaunchId", "1535356616730", false, false);
            yield return request38;
            request38 = null;

            WebTestRequest request39 = new WebTestRequest("https://admingate-emea.saacon.net/Citrix/XenApp/site/appembed.aspx");
            request39.QueryStringParameters.Add("CTX_Application", "Citrix.MPS.App.AdmingateSaaconV2.BMW%20Europe%20Farm%20managed%20by%20customer_DE" +
                    "", false, false);
            request39.QueryStringParameters.Add("CTX_AppFriendlyNameURLENcoded", "BMW%20Europe%20Farm%20managed%20by%20customer_DE", false, false);
            request39.QueryStringParameters.Add("CTX_Token", "5981BE6EABA4F2603F83576BEBEEFB36", false, false);
            request39.QueryStringParameters.Add("LaunchId", "1535356616730", false, false);
            request39.QueryStringParameters.Add("CTX_WindowWidth", "1438", false, false);
            request39.QueryStringParameters.Add("CTX_WindowHeight", "808", false, false);
            request39.QueryStringParameters.Add("Title", "BMW%20Europe%20Farm%20managed%20by%20customer_DE", false, false);
            yield return request39;
            request39 = null;
        }
    }
}
